login:
    path: /auth
    controller: App\Controller\AuthController:login
infos:
    path: /infos
    controller: App\Controller\InfosController:index
getPosts:
    path: /infos/posts
    controller: App\Controller\InfosController:getInfosPosts
getInfoByPost:
    path: /infos/post/{post}
    controller: App\Controller\InfosController:getInfosByPost
getTeams:
    path: /infos/teams
    controller: App\Controller\InfosController:getInfosTeams
getInfoByTeam:
    path: /infos/team/{team}
    controller: App\Controller\InfosController:getInfosByTeam
getAgencies:
    path: /infos/agencies
    controller: App\Controller\InfosController:getInfosAgencies
getInfoByAgency:
    path: /infos/agency/{agency}
    controller: App\Controller\InfosController:getInfosByAgency
postEmployee:
    path: /infos/employee
    controller: App\Controller\InfosController:postEmployee
    methods: [POST]
patchEmployee:
    path: /infos/employee/{id}
    controller: App\Controller\InfosController:postEmployee
    methods: [PATCH]
addUser:
    path: /auth/addUser
    controller: App\Controller\AuthController:addUser
deleteUser:
    path: /auth/deleteUser
    controller: App\Controller\AuthController:deleteUser
getAllUsers:
    path: /auth/users
    controller: App\Controller\AuthController:getAllUser
initDb:
    path: /init
    controller: App\Controller\DbController:index
verifyToken:
    path: /auth/check
    controller: App\Controller\AuthController:verifyToken