version: '3'

services:
    # Service pour le serveur web
    web:
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: ubuntu:latest
        container_name: backend_web
        restart: unless-stopped
        ports:
            - "8080:8000"
        command: sh -c "symfony serve --allow-http --no-tls"
        volumes:
            - ./symfony:/var/www/html
        depends_on:
            - php

    # Service pour PHP-FPM
    php:
        image: php:8.1.27-fpm
        container_name: backend_php
        restart: unless-stopped
        volumes:
            - ./symfony:/var/www/html


networks:
    mon_projet_net:
        driver: bridge
