version: '3'

services:
    database:
        container_name: backend_database
        image: postgres:12.8
        env_file:
            - ./backend/.env
        ports:
            - '5432:5432'
        volumes:
            - db:/var/lib/postgresql/data
        restart: always
    web:
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: ubuntu:latest
        container_name: backend_web
        restart: unless-stopped
        ports:
            - "8000:8000"
        command: sh -c "symfony serve --allow-http --no-tls"
        env_file:
            - backend/.env
        volumes:
            - ./symfony:/var/www/html

    front:
        build:
            context: ./front-end/app
            dockerfile: Dockerfile

        container_name: front_web
        restart: unless-stopped
        ports:
            - "8080:8080"

networks:
    mon_projet_net:
        driver: bridge

volumes:
    db_data:
    db:
