name: actions

on:
  push:
    branches:
      - main

jobs:
  pushContent:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY}}

      - name: Cat is good
        run: echo ${{ env.MIRROR_URL }}

      
